require 'bundler/gem_tasks'
require 'rspec/core/rake_task'
require 'rubocop/rake_task'

RuboCop::RakeTask.new do |rubocop|
  rubocop.verbose = false
end

RSpec::Core::RakeTask.new(:spec) do |spec|
  spec.verbose = false
end

task default: [:rubocop, :spec]
