require 'bundler/gem_tasks'
require 'rspec/core/rake_task'
require 'rubocop/rake_task'

RuboCop::RakeTask.new do |rubocop|
  # TODO: rubocop-rspec falls over
  # rubocop.requires = %w(rubocop-rspec)
  # rubocop.verbose = false
end

RSpec::Core::RakeTask.new(:spec) do |spec|
  spec.verbose = false
end

task default: [:rubocop, :spec]
